CREATE TABLE reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  date_of_birth DATE,
  gender VARCHAR(50),
  education VARCHAR(255),
  smoking VARCHAR(50),
  alcohol VARCHAR(50),
  total_income DECIMAL(15,2),
  income_stability VARCHAR(100),
  retirement_age INT,
  monthly_expenses DECIMAL(15,2),
  loan_amount DECIMAL(15,2),
  upcoming_expenses DECIMAL(15,2),
  total_investments DECIMAL(15,2),
  life_cover_amount DECIMAL(15,2),
  education_expenses DECIMAL(15,2),
  wedding_expenses DECIMAL(15,2),
  number_of_kids INT,
  calculated_coverage DECIMAL(15,2),
  inflation_adjusted_expenses DECIMAL(15,2),
  recommended_coverage DECIMAL(15,2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 